### PR TITLE
Add training debug mode

### LINKED ISSUE #30: Clean up output when uploading to train
Let's hide everything after the url so it's easier to see the url.

### LINKED ISSUE #39: Simulation train method breaks if there are any other zip files in the directory
When there are any other zip files in the directory, when `simulation.train()` is called, seems like it falls in an endless loop and creates many training.zip files within themselves and ends up exploding in size.
Screen Shot 2021-11-03 at 5 29 29 PM
.

### PR DESCRIPTION
**Pull request by slinlee**
- Clean up the default output from `.train()`
- Add Troubleshooting guide to the readme
- Delete the training.zip file unless in debug_mode

Before

image

After

Screen Shot 2021-11-07 at 2 29 17 AM

Resolves #30, Fixes #39

### CODE REVIEW

**Review by maxpumperla — APPROVED** [review]
thanks, really good catch!

**Comment by maxpumperla** [comment]
@slinlee my bad on the merge

**Comment by slinlee** [comment]
> @slinlee my bad on the merge

It's great how much even these basic tests have caught though! @maxpumperla

**Comment by SaharEs** [comment]
Issue #39 still is happening on my side. It gets stuck in this line and `training.zip` size explodes.
        https://github.com/PathmindAI/pathmind-api/blob/70d05480059beb2f96fcaa2cec3e0fedf4eff070/pathmind/simulation.py#L206

**Pull request merged**
