### PR TITLE
add support for gym environments

### PR DESCRIPTION
**Pull request by maxpumperla**

### CODE REVIEW

**Comment by slinlee** [comment]
@ejunprung I didn't have time to test this today, but it looks good. You should give it a spin!

**Comment by ejunprung** [comment]
I'm not sure if I'm doing this correctly but I'm getting the below.

```
>>> from pathmind.simulation import from_gym
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'from_gym' from 'pathmind.simulation' (/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pathmind/simulation.py)
```

**Comment by slinlee** [comment]
It's likely your python env is using the installed pathmind package and not this local change. Try `pip install .` in this repo

**Comment by maxpumperla** [comment]
@ejunprung clone the repo and install like shown on the readme, or install from GitHub like I've indicated in Slack.

**Comment by ejunprung** [comment]
Ah, I had to `pip uninstall pathmind` first and then `python setup.py install` to update. It seems to work now.

**Review by ejunprung — APPROVED** [review]
Ignoring the requirements.txt issue, I've tested and it seems to work.

**Comment by slinlee** [comment]
@ejunprung do you still need this branch now?

**Comment by ejunprung** [comment]
Nope, you can delete it

**Pull request merged**
